/**
 * this occurs when other player streams are received by webrtc
 */
export const EVENT_RECEIVED_USER_MEDIA_STREAM =
  'EVENT_RECEIVED_USER_MEDIA_STREAM'
export const EVENT_CAMERA_START_FOLLOW_PLAYER =
  'EVENT_CAMERA_START_FOLLOW_PLAYER'
export const EVENT_OPEN_GAME_OBJECT_SETTINGS = 'EVENT_OPEN_GAME_OBJECT_SETTINGS'
export const EVENT_FREE_OCCUPIED_TILES = 'EVENT_FREE_OCCUPIED_TILES'
export const EVENT_OPEN_INTERACTION_MENU = 'EVENT_OPEN_INTERACTION_MENU'
export const EVENT_GAME_OBJECT_CLICK = 'EVENT_GAME_OBJECT_CLICK'
