apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  selector:
    app: app
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer
