apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v2.1.1
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: "$HASURA_GRAPHQL_DATABASE_URL"
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          value: "$HASURA_GRAPHQL_ADMIN_SECRET"
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_JWT_SECRET
          value: '$HASURA_GRAPHQL_JWT_SECRET'
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
