apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
  namespace: default
spec:
  selector:
    app: auth
  ports:
  - name: https
    port: 443
    targetPort: 4000
  - name: http
    port: 80
    targetPort: 4000
  - name: ws
    port: 4001
    targetPort: 4001

  type: LoadBalancer
